### ISSUE TITLE
Can I use this to get data from an RRD Databse, located on another device?

### ISSUE THREAD

**Issue by compumark** [dgomes/rrd_recorder#11]
Hi,
I am trying to start with my home assistant integration. I have since years an old raspberry pi running and collecting data from my Viessmann heat pump to an rrd database on the raspberry directly. 
Is it possible to grad the data from the raspberry rrd to display it in HA ? 
thanks a lot,
Mark

**Comment by dgomes** [comment]
yes, this is the integration for that :)

**Comment by compumark** [comment]
Than I "only" need to figure out how I can mount the rrdb database from the raspberry pi, which is running on the network to the HA docker running instance 🫣

**Comment by dgomes** [comment]
that is out of scope of this integration nonetheless 😓
