### ISSUE TITLE
May I ask for help to Install on HA on docker 

### ISSUE THREAD

**Issue by leonidostrovski** [dgomes/rrd_recorder#14]
Hi
May I ask for help to Install on HA on docker.
I stuck on an error during "check configuration":
"Configuration warnings - Setup of package 'rrd' failed: Requirements for rrd_recorder not found: ['rrdtool==0.1.15'].

The RRD Recorder downloaded from HAS.
In  the OS with docker ran "apt-get install librrd-dev libpython3-dev"

Thanks

**Comment by dgomes** [comment]
HA Docker image does not contain rrdtool 

Therefore this custom component does not work in neither Docker or OS install

Sorry about that
