### ISSUE TITLE
Some step intervals skipped when sensor are changing less often

### ISSUE THREAD

**Issue by ma-zal** [dgomes/rrd_recorder#2]
Currently sensor's data are collected and saved based on the change event `EVENT_STATE_CHANGED`.

Issue: When values are changing less often then `step` interval of RRD database, therefore some steps are skipped (not stored) in RRD database.

Maybe better behavior can be the time based getting+saving (not the event based). There can be a timer, which will every `step` interval get and store all current values of all mesured sensors.

Consequently it will make the code more simple, because no caching in `entities ` variable will be needed anymore. :-)

**Comment by dgomes** [comment]
Good point!

I'll try to come up with something, but if want to have a go I would gladly accept a PR

**Comment by ma-zal** [comment]
Resolved by pull request https://github.com/dgomes/rrd_recorder/pull/3
Closing.
